### ISSUE TITLE
Please read the section on async stuff in Capybara's README

### ISSUE THREAD

**Issue by jnicklas** [chriserin/patientgeist#1]
Hi there, just happened to see this, and wanted to let you know that Capybara provides quite sophisticated tools for waiting on content built in, there are very few reasons to have to wait for AJAX requests if you're using Capybara properly.

The README talks about this some and I also detailed some of this stuff in a blog post a while ago: http://www.elabs.se/blog/53-why-wait_until-was-removed-from-capybara.

Capybara used to have something similar to what you're doing here built in, but we removed it because it was no longer necessary.

**Comment by chriserin** [comment]
Thanks Jonas!  I'm not very experienced in capybara and wasn't aware that
the capybara matchers were implemented with the synchronize method, so I
appreciate the link!

In defense of my solution, I have some very minor complaints.

1)  Its not intuitive that some matchers behave differently than others,
however, that they come from different libraries indicates that they could.

2)  The synchronized matchers take 2 seconds to fail, rather than failing
immediately as the rspec matchers do.  (tho I appreciate the sophistication
built into failing from synchronize as soon as possible)

The patientgeist solution is very much a hack, which I wouldn't recommend
for anybody.  What I would want from poltergeist is to wait for all http
requests to complete before returning from the click, mouse_event, visit,
etc methods and I would like that behavior to be configurable.  That type
of solution is prevented by this defect:
https://github.com/ariya/phantomjs/issues/10498 because poltergeist never
receives the onResourceReceived event in some cases.

Regardless, I'll make better use of the capybara matchers now!

**Comment by jnicklas** [comment]
1) Yes, this is somewhat tricky, if you're using someone else's matchers and they are not built well, you are going to run into problems. There is some burden here on authors of matchers to get it right, which is why it's especially important to understand the benefits and risks of Capybara's synchronization behaviour.

2) Yes, they do take a little while to fail, but I don't tend to find that this is a problem, Rails boot time, Firefox upstart time, etc.. make running a single scenario so slow anyway that those additional two seconds don't really matter, and it's a small price to pay for eliminating so many race-conditions.

Waiting for AJAX requests is an often proposed solution, but you'll find that it doesn't really work. As your JavaScript becomes more and more sophisticated you'll see other asynchronous processes, like `setInterval`, `requestAnimationFrame` and `setTimeout`, and you can't really wait for these, since they may be perpetually occuring so you end up waiting indefinitely. So you end up with flickering tests anyway.

**Comment by chriserin** [comment]
Yeah its a super interesting problem, with different varieties of
trade-offs.

On #2.  With Rails 4.1 having spring built-in, and using phantomjs, which
upstarts quickly, those 2 seconds may become more evident, but like you
said, its a small price to pay to avoid race conditions.

I haven't had the opportunity to test other asynchronous js methods like
you've mentioned, and I look forward to encountering that problem.  For my
own curiosity I want to pursue waiting for requests in poltergeist, but it
certainly won't make capybara's sophistication on this issue any less
necessary.
Cheers!
